version: "3"
services:
  couchbase:
    image: escapedcanadian/couchmovies-couchbase:latest
    container_name: couchbase
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"

  movieservice:
    image: escapedcanadian/couchmovies-movieservice:latest
    container_name: movieservice
    depends_on: 
      - couchbase
    ports: 
      - "8080:8080"

  web:
    image: escapedcanadian/couchmovies-web:latest
    depends_on:
      - movieservice
      - couchbase
    ports: 
      - "8000:8000"
 